version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_docker_engine

      - run:
          name: Build Project and Run Tests
          command: mvn clean install

      - run:
          name: Coverage Metrics
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Sonar Analysis
          command: mvn sonar:sonar \
            -Dsonar.projectKey=lorenzomartino86_money-transfer-app \
            -Dsonar.organization=lorenzomartino86 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=59c9c092c9062baf91d4e31672fdd420d35ad767


command: docker stop $(docker ps -a -q)