version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - setup_docker_engine

      - run:
          name: Build Project and Run Tests
          command: mvn clean install

command: docker stop $(docker ps -a -q)